[build]
  functions = "netlify/functions"
  publish = "." # This tells Netlify where your static files (like index.html) are

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
