[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  # Node.js version is now handled by .nvmrc in netlify/functions/
  external_node_modules = ["node-fetch"] # Explicitly include node-fetch for bundling
