[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild" # This can sometimes help with module resolution
  node_version = "18" # Or "20", a recent LTS version
