[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  # To set Node.js version, use a .nvmrc file in netlify/functions/
  # or set NODE_VERSION as an environment variable in Netlify UI
